package com.example.demo;

import java.util.ArrayList;
import java.util.List;

/**
 * In-memory product catalog for demo.
 */
public final class ProductCatalog {

    private ProductCatalog() {}

    public static List<Product> getFashionProducts() {
        List<Product> all = new ArrayList<>();

        // Baby category (70 items)
        all.add(new Product("F001", "Baby Romper Set", "Fashion", "Baby", 450, 20));
        all.add(new Product("F002", "Baby Cotton Dress", "Fashion", "Baby", 550, 15));
        all.add(new Product("F003", "Baby Onesie Pack", "Fashion", "Baby", 650, 0));
        all.add(new Product("F004", "Baby Summer Shorts", "Fashion", "Baby", 350, 25));
        all.add(new Product("F005", "Baby Winter Jacket", "Fashion", "Baby", 1200, 30));
        all.add(new Product("F006", "Baby Sleepwear Set", "Fashion", "Baby", 500, 10));
        all.add(new Product("F007", "Baby Party Dress", "Fashion", "Baby", 800, 0));
        all.add(new Product("F008", "Baby Denim Dungaree", "Fashion", "Baby", 700, 15));
        all.add(new Product("F009", "Baby Knit Sweater", "Fashion", "Baby", 600, 20));
        all.add(new Product("F010", "Baby Bodysuit Pack (5pcs)", "Fashion", "Baby", 900, 0));
        all.add(new Product("F011", "Baby Cotton T-Shirt", "Fashion", "Baby", 300, 18));
        all.add(new Product("F012", "Baby Jogger Pants", "Fashion", "Baby", 400, 12));
        all.add(new Product("F013", "Baby Frock", "Fashion", "Baby", 750, 22));
        all.add(new Product("F014", "Baby Hoodie", "Fashion", "Baby", 650, 0));
        all.add(new Product("F015", "Baby Cardigan", "Fashion", "Baby", 550, 15));
        all.add(new Product("F016", "Baby Swim Suit", "Fashion", "Baby", 450, 20));
        all.add(new Product("F017", "Baby Pajama Set", "Fashion", "Baby", 500, 10));
        all.add(new Product("F018", "Baby Overall", "Fashion", "Baby", 800, 25));
        all.add(new Product("F019", "Baby Track Suit", "Fashion", "Baby", 900, 0));
        all.add(new Product("F020", "Baby Rain Coat", "Fashion", "Baby", 600, 15));
        all.add(new Product("F021", "Baby Polo Shirt", "Fashion", "Baby", 400, 18));
        all.add(new Product("F022", "Baby Leggings", "Fashion", "Baby", 300, 12));
        all.add(new Product("F023", "Baby Formal Dress", "Fashion", "Baby", 1000, 28));
        all.add(new Product("F024", "Baby Ethnic Wear", "Fashion", "Baby", 850, 20));
        all.add(new Product("F025", "Baby Blazer", "Fashion", "Baby", 1200, 0));
        all.add(new Product("F026", "Baby Vest Set", "Fashion", "Baby", 500, 15));
        all.add(new Product("F027", "Baby Denim Jacket", "Fashion", "Baby", 950, 22));
        all.add(new Product("F028", "Baby Fleece Hoodie", "Fashion", "Baby", 700, 18));
        all.add(new Product("F029", "Baby Sports Wear", "Fashion", "Baby", 600, 0));
        all.add(new Product("F030", "Baby Graphic Tee", "Fashion", "Baby", 350, 15));
        all.add(new Product("F031", "Baby Cargo Pants", "Fashion", "Baby", 550, 20));
        all.add(new Product("F032", "Baby Tutu Skirt", "Fashion", "Baby", 650, 25));
        all.add(new Product("F033", "Baby Rainwear", "Fashion", "Baby", 750, 0));
        all.add(new Product("F034", "Baby Winter Sweater", "Fashion", "Baby", 800, 18));
        all.add(new Product("F035", "Baby Casual Shirt", "Fashion", "Baby", 450, 12));
        all.add(new Product("F036", "Baby Jumpsuit", "Fashion", "Baby", 700, 22));
        all.add(new Product("F037", "Baby Night Suit", "Fashion", "Baby", 500, 0));
        all.add(new Product("F038", "Baby Shrug", "Fashion", "Baby", 400, 15));
        all.add(new Product("F039", "Baby Ethnic Kurta", "Fashion", "Baby", 900, 20));
        all.add(new Product("F040", "Baby Bomber Jacket", "Fashion", "Baby", 1100, 25));
        all.add(new Product("F041", "Baby Sweatshirt", "Fashion", "Baby", 600, 0));
        all.add(new Product("F042", "Baby Printed Shorts", "Fashion", "Baby", 350, 18));
        all.add(new Product("F043", "Baby Festive Dress", "Fashion", "Baby", 1200, 30));
        all.add(new Product("F044", "Baby Capri Pants", "Fashion", "Baby", 450, 12));
        all.add(new Product("F045", "Baby Tank Top", "Fashion", "Baby", 250, 0));
        all.add(new Product("F046", "Baby Puffer Jacket", "Fashion", "Baby", 1300, 25));
        all.add(new Product("F047", "Baby Dungaree Shorts", "Fashion", "Baby", 650, 15));
        all.add(new Product("F048", "Baby Skirt Set", "Fashion", "Baby", 700, 20));
        all.add(new Product("F049", "Baby Thermal Wear", "Fashion", "Baby", 550, 0));
        all.add(new Product("F050", "Baby Beach Wear", "Fashion", "Baby", 400, 18));
        all.add(new Product("F051", "Baby Velvet Dress", "Fashion", "Baby", 1100, 22));
        all.add(new Product("F052", "Baby Casual Combo", "Fashion", "Baby", 900, 0));
        all.add(new Product("F053", "Baby Quilted Jacket", "Fashion", "Baby", 950, 20));
        all.add(new Product("F054", "Baby Party Wear", "Fashion", "Baby", 1400, 28));
        all.add(new Product("F055", "Baby Tights", "Fashion", "Baby", 300, 10));
        all.add(new Product("F056", "Baby Jogger Set", "Fashion", "Baby", 800, 0));
        all.add(new Product("F057", "Baby Designer Dress", "Fashion", "Baby", 1600, 30));
        all.add(new Product("F058", "Baby Cotton Shorts", "Fashion", "Baby", 350, 15));
        all.add(new Product("F059", "Baby Henley Shirt", "Fashion", "Baby", 500, 12));
        all.add(new Product("F060", "Baby Windbreaker", "Fashion", "Baby", 850, 0));
        all.add(new Product("F061", "Baby Layering Tee", "Fashion", "Baby", 300, 18));
        all.add(new Product("F062", "Baby Festive Kurta", "Fashion", "Baby", 1000, 25));
        all.add(new Product("F063", "Baby Pullover", "Fashion", "Baby", 700, 15));
        all.add(new Product("F064", "Baby Printed Dress", "Fashion", "Baby", 650, 0));
        all.add(new Product("F065", "Baby Casual Pants", "Fashion", "Baby", 500, 20));
        all.add(new Product("F066", "Baby Zip Hoodie", "Fashion", "Baby", 750, 18));
        all.add(new Product("F067", "Baby Denim Shorts", "Fashion", "Baby", 450, 0));
        all.add(new Product("F068", "Baby Athletic Wear", "Fashion", "Baby", 600, 22));
        all.add(new Product("F069", "Baby Sherpa Jacket", "Fashion", "Baby", 1200, 25));
        all.add(new Product("F070", "Baby Occasion Wear", "Fashion", "Baby", 1500, 30));

        // Male category (70 items)
        all.add(new Product("F071", "Men's Casual Shirt", "Fashion", "Male", 1200, 25));
        all.add(new Product("F072", "Men's Polo T-Shirt", "Fashion", "Male", 800, 10));
        all.add(new Product("F073", "Men's Formal Pant", "Fashion", "Male", 1500, 0));
        all.add(new Product("F074", "Men's Denim Jeans", "Fashion", "Male", 1800, 30));
        all.add(new Product("F075", "Men's Kurta", "Fashion", "Male", 1000, 15));
        all.add(new Product("F076", "Men's Panjabi", "Fashion", "Male", 1400, 20));
        all.add(new Product("F077", "Men's Blazer", "Fashion", "Male", 3500, 0));
        all.add(new Product("F078", "Men's Winter Jacket", "Fashion", "Male", 2800, 25));
        all.add(new Product("F079", "Men's Hoodie", "Fashion", "Male", 1600, 18));
        all.add(new Product("F080", "Men's Track Pants", "Fashion", "Male", 900, 12));
        all.add(new Product("F081", "Men's Shorts", "Fashion", "Male", 600, 0));
        all.add(new Product("F082", "Men's Graphic T-Shirt", "Fashion", "Male", 500, 20));
        all.add(new Product("F083", "Men's Formal Shirt", "Fashion", "Male", 1300, 15));
        all.add(new Product("F084", "Men's Sweater", "Fashion", "Male", 1100, 10));
        all.add(new Product("F085", "Men's Vest", "Fashion", "Male", 700, 0));
        all.add(new Product("F086", "Men's Cotton Shirt", "Fashion", "Male", 950, 18));
        all.add(new Product("F087", "Men's Chinos", "Fashion", "Male", 1400, 22));
        all.add(new Product("F088", "Men's Leather Jacket", "Fashion", "Male", 4500, 28));
        all.add(new Product("F089", "Men's Sweatshirt", "Fashion", "Male", 1200, 0));
        all.add(new Product("F090", "Men's Cargo Pants", "Fashion", "Male", 1300, 15));
        all.add(new Product("F091", "Men's Sports Jersey", "Fashion", "Male", 800, 20));
        all.add(new Product("F092", "Men's V-Neck Tee", "Fashion", "Male", 450, 12));
        all.add(new Product("F093", "Men's Bomber Jacket", "Fashion", "Male", 2500, 0));
        all.add(new Product("F094", "Men's Ethnic Wear", "Fashion", "Male", 1600, 25));
        all.add(new Product("F095", "Men's Cardigan", "Fashion", "Male", 1400, 18));
        all.add(new Product("F096", "Men's Tank Top", "Fashion", "Male", 400, 0));
        all.add(new Product("F097", "Men's Joggers", "Fashion", "Male", 1000, 20));
        all.add(new Product("F098", "Men's Pullover", "Fashion", "Male", 1200, 15));
        all.add(new Product("F099", "Men's Henley Shirt", "Fashion", "Male", 750, 0));
        all.add(new Product("F100", "Men's Windbreaker", "Fashion", "Male", 1800, 22));
        all.add(new Product("F101", "Men's Linen Shirt", "Fashion", "Male", 1100, 18));
        all.add(new Product("F102", "Men's Slim Fit Jeans", "Fashion", "Male", 1900, 25));
        all.add(new Product("F103", "Men's Fleece Jacket", "Fashion", "Male", 2000, 0));
        all.add(new Product("F104", "Men's Printed Tee", "Fashion", "Male", 500, 15));
        all.add(new Product("F105", "Men's Trench Coat", "Fashion", "Male", 3800, 30));
        all.add(new Product("F106", "Men's Nehru Jacket", "Fashion", "Male", 2200, 20));
        all.add(new Product("F107", "Men's Athletic Shorts", "Fashion", "Male", 650, 0));
        all.add(new Product("F108", "Men's Denim Jacket", "Fashion", "Male", 2400, 25));
        all.add(new Product("F109", "Men's Turtleneck", "Fashion", "Male", 1300, 12));
        all.add(new Product("F110", "Men's Oxford Shirt", "Fashion", "Male", 1500, 0));
        all.add(new Product("F111", "Men's Puffer Jacket", "Fashion", "Male", 2800, 28));
        all.add(new Product("F112", "Men's Rugby Shirt", "Fashion", "Male", 900, 18));
        all.add(new Product("F113", "Men's Sherwani", "Fashion", "Male", 4000, 0));
        all.add(new Product("F114", "Men's Thermal Wear", "Fashion", "Male", 800, 15));
        all.add(new Product("F115", "Men's Beach Shorts", "Fashion", "Male", 550, 20));
        all.add(new Product("F116", "Men's Suit Jacket", "Fashion", "Male", 3200, 25));
        all.add(new Product("F117", "Men's Flannel Shirt", "Fashion", "Male", 1100, 0));
        all.add(new Product("F118", "Men's Muscle Tee", "Fashion", "Male", 400, 18));
        all.add(new Product("F119", "Men's Track Jacket", "Fashion", "Male", 1400, 22));
        all.add(new Product("F120", "Men's Corduroy Pants", "Fashion", "Male", 1600, 0));
        all.add(new Product("F121", "Men's Zip Hoodie", "Fashion", "Male", 1500, 20));
        all.add(new Product("F122", "Men's Designer Kurta", "Fashion", "Male", 1800, 25));
        all.add(new Product("F123", "Men's Quilted Jacket", "Fashion", "Male", 2600, 28));
        all.add(new Product("F124", "Men's Hawaiian Shirt", "Fashion", "Male", 900, 0));
        all.add(new Product("F125", "Men's Skinny Jeans", "Fashion", "Male", 1700, 18));
        all.add(new Product("F126", "Men's Parka Jacket", "Fashion", "Male", 3200, 30));
        all.add(new Product("F127", "Men's Longline Tee", "Fashion", "Male", 600, 15));
        all.add(new Product("F128", "Men's Waistcoat", "Fashion", "Male", 1400, 0));
        all.add(new Product("F129", "Men's Tracksuit", "Fashion", "Male", 2200, 25));
        all.add(new Product("F130", "Men's Denim Shirt", "Fashion", "Male", 1200, 20));
        all.add(new Product("F131", "Men's Blazer Suit", "Fashion", "Male", 4200, 0));
        all.add(new Product("F132", "Men's Gym Shorts", "Fashion", "Male", 500, 18));
        all.add(new Product("F133", "Men's Rain Jacket", "Fashion", "Male", 1900, 22));
        all.add(new Product("F134", "Men's Biker Jacket", "Fashion", "Male", 3800, 28));
        all.add(new Product("F135", "Men's Capri Pants", "Fashion", "Male", 800, 0));
        all.add(new Product("F136", "Men's Party Shirt", "Fashion", "Male", 1600, 25));
        all.add(new Product("F137", "Men's Lounge Pants", "Fashion", "Male", 900, 15));
        all.add(new Product("F138", "Men's Winter Coat", "Fashion", "Male", 3500, 30));
        all.add(new Product("F139", "Men's Striped Tee", "Fashion", "Male", 550, 0));
        all.add(new Product("F140", "Men's Formal Suit", "Fashion", "Male", 5000, 20));

        // Female category (70 items)
        all.add(new Product("F141", "Women's Kurti", "Fashion", "Female", 950, 20));
        all.add(new Product("F142", "Women's Saree", "Fashion", "Female", 2500, 15));
        all.add(new Product("F143", "Women's Top", "Fashion", "Female", 700, 0));
        all.add(new Product("F144", "Women's Salwar Kameez", "Fashion", "Female", 1600, 25));
        all.add(new Product("F145", "Women's Palazzo Set", "Fashion", "Female", 1200, 18));
        all.add(new Product("F146", "Women's Jeans", "Fashion", "Female", 1400, 22));
        all.add(new Product("F147", "Women's Maxi Dress", "Fashion", "Female", 1800, 0));
        all.add(new Product("F148", "Women's Lehenga Choli", "Fashion", "Female", 3500, 30));
        all.add(new Product("F149", "Women's Winter Shawl", "Fashion", "Female", 1100, 12));
        all.add(new Product("F150", "Women's Tunic Top", "Fashion", "Female", 850, 15));
        all.add(new Product("F151", "Women's Cardigan", "Fashion", "Female", 1300, 0));
        all.add(new Product("F152", "Women's Anarkali Suit", "Fashion", "Female", 2200, 20));
        all.add(new Product("F153", "Women's Ethnic Gown", "Fashion", "Female", 2800, 25));
        all.add(new Product("F154", "Women's Blouse", "Fashion", "Female", 600, 10));
        all.add(new Product("F155", "Women's Skirt", "Fashion", "Female", 900, 0));
        all.add(new Product("F156", "Women's Designer Saree", "Fashion", "Female", 4500, 28));
        all.add(new Product("F157", "Women's Cotton Kurti", "Fashion", "Female", 750, 18));
        all.add(new Product("F158", "Women's Leggings", "Fashion", "Female", 500, 12));
        all.add(new Product("F159", "Women's Party Dress", "Fashion", "Female", 2200, 0));
        all.add(new Product("F160", "Women's Denim Jacket", "Fashion", "Female", 1800, 22));
        all.add(new Product("F161", "Women's Formal Shirt", "Fashion", "Female", 1200, 15));
        all.add(new Product("F162", "Women's Jumpsuit", "Fashion", "Female", 1600, 0));
        all.add(new Product("F163", "Women's Printed Kurti", "Fashion", "Female", 850, 20));
        all.add(new Product("F164", "Women's Sharara Set", "Fashion", "Female", 2400, 25));
        all.add(new Product("F165", "Women's Casual Top", "Fashion", "Female", 650, 18));
        all.add(new Product("F166", "Women's Silk Saree", "Fashion", "Female", 3200, 0));
        all.add(new Product("F167", "Women's Sweater", "Fashion", "Female", 1100, 15));
        all.add(new Product("F168", "Women's Shorts", "Fashion", "Female", 600, 20));
        all.add(new Product("F169", "Women's Ethnic Jacket", "Fashion", "Female", 1800, 22));
        all.add(new Product("F170", "Women's Hoodie", "Fashion", "Female", 1400, 0));
        all.add(new Product("F171", "Women's Patiala Suit", "Fashion", "Female", 1500, 18));
        all.add(new Product("F172", "Women's T-Shirt", "Fashion", "Female", 500, 12));
        all.add(new Product("F173", "Women's Evening Gown", "Fashion", "Female", 3800, 30));
        all.add(new Product("F174", "Women's Shrug", "Fashion", "Female", 800, 0));
        all.add(new Product("F175", "Women's Capri Pants", "Fashion", "Female", 700, 15));
        all.add(new Product("F176", "Women's Blazer", "Fashion", "Female", 2500, 25));
        all.add(new Product("F177", "Women's Long Kurti", "Fashion", "Female", 1000, 20));
        all.add(new Product("F178", "Women's Denim Jeans", "Fashion", "Female", 1500, 0));
        all.add(new Product("F179", "Women's Chiffon Saree", "Fashion", "Female", 2800, 22));
        all.add(new Product("F180", "Women's Crop Top", "Fashion", "Female", 600, 18));
        all.add(new Product("F181", "Women's Palazzo Pants", "Fashion", "Female", 900, 0));
        all.add(new Product("F182", "Women's Winter Jacket", "Fashion", "Female", 2400, 25));
        all.add(new Product("F183", "Women's Formal Pants", "Fashion", "Female", 1300, 15));
        all.add(new Product("F184", "Women's Indo-Western", "Fashion", "Female", 2600, 28));
        all.add(new Product("F185", "Women's Tank Top", "Fashion", "Female", 450, 0));
        all.add(new Product("F186", "Women's Gharara Set", "Fashion", "Female", 2200, 20));
        all.add(new Product("F187", "Women's Sweatshirt", "Fashion", "Female", 1200, 18));
        all.add(new Product("F188", "Women's Skater Dress", "Fashion", "Female", 1400, 0));
        all.add(new Product("F189", "Women's Velvet Lehenga", "Fashion", "Female", 4200, 30));
        all.add(new Product("F190", "Women's Jeggings", "Fashion", "Female", 800, 15));
        all.add(new Product("F191", "Women's Bodycon Dress", "Fashion", "Female", 1600, 22));
        all.add(new Product("F192", "Women's Kaftan", "Fashion", "Female", 1100, 0));
        all.add(new Product("F193", "Women's Straight Kurti", "Fashion", "Female", 900, 18));
        all.add(new Product("F194", "Women's Designer Gown", "Fashion", "Female", 3500, 25));
        all.add(new Product("F195", "Women's Track Pants", "Fashion", "Female", 750, 12));
        all.add(new Product("F196", "Women's Peplum Top", "Fashion", "Female", 850, 0));
        all.add(new Product("F197", "Women's Banarasi Saree", "Fashion", "Female", 4000, 28));
        all.add(new Product("F198", "Women's Tunic Dress", "Fashion", "Female", 1300, 20));
        all.add(new Product("F199", "Women's Wrap Dress", "Fashion", "Female", 1500, 0));
        all.add(new Product("F200", "Women's A-Line Kurti", "Fashion", "Female", 950, 18));
        all.add(new Product("F201", "Women's Cocktail Dress", "Fashion", "Female", 2500, 25));
        all.add(new Product("F202", "Women's Printed Palazzo", "Fashion", "Female", 800, 15));
        all.add(new Product("F203", "Women's Shirt Dress", "Fashion", "Female", 1400, 0));
        all.add(new Product("F204", "Women's Kurta Set", "Fashion", "Female", 1800, 22));
        all.add(new Product("F205", "Women's Off-Shoulder Top", "Fashion", "Female", 900, 18));
        all.add(new Product("F206", "Women's Silk Kurti", "Fashion", "Female", 1600, 20));
        all.add(new Product("F207", "Women's Party Gown", "Fashion", "Female", 3200, 28));
        all.add(new Product("F208", "Women's Casual Shirt", "Fashion", "Female", 1000, 0));
        all.add(new Product("F209", "Women's Festive Wear", "Fashion", "Female", 2800, 30));
        all.add(new Product("F210", "Women's Layered Dress", "Fashion", "Female", 1700, 25));

        return all;
    }
}
